# Generated by Django 2.2.4 on 2019-09-16 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beaconofhopeapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Referralsource',
        ),
    ]
