# Generated by Django 2.2.4 on 2019-09-16 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beaconofhopeapp', '0002_delete_referralsource'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralSource',
            fields=[
                ('id', models.CharField(db_column='Id', max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'ReferralSource',
                'managed': False,
            },
        ),
    ]
