# Generated by Django 2.2.4 on 2019-09-17 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beaconofhopeapp', '0003_referralsource'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'managed': False, 'ordering': ['id']},
        ),
    ]
